// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20180115145519_ColumnUpdates")]
    partial class ColumnUpdates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Department");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("EmployeeStatus");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("FavoriteColor");

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("ImageFileName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Manager");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Shift");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WebApplication1.Models.Permissions", b =>
                {
                    b.Property<int>("EmployeeID");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateRemoved");

                    b.Property<int?>("Type");

                    b.HasKey("EmployeeID");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("WebApplication1.Models.Permissions", b =>
                {
                    b.HasOne("WebApplication1.Models.Employee", "Employee")
                        .WithOne("Permissions")
                        .HasForeignKey("WebApplication1.Models.Permissions", "EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
